apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-pod1
  template:
    metadata:
      labels:
        app: app-pod1
    spec:
      containers:
      - name: test-api
        image: ${{ secrets.DOCKER_USERNAME }}/tradingapp:${{github.sha}}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

----------

apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    type: NodePort
    selector:
        app: app-pod1
    ports:
        - port: 8080
          targetPort: 8080
