name: Build and Push Docker Image

on:
  push:
    branches:
      - master # You can adjust this to your main branch name

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -f TradingAPI\Dockerfile --force-rm -t smitshah1991/tradingapp .

    - name: Push Docker image
      run: docker push smitshah1991/tradingapp
