name: Build and Push Docker Image

on:
  push:
    branches:
      - master # You can adjust this to your main branch name
    paths-ignore:
      -gitignore
      -.vs/**
  workflow_dispatch:      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./TradingAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tradingapp:${{github.sha}}
  Miniube:
   runs-on: ubuntu-latest
   name: build example and deploy to minikube
   steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Deploy to minikube
      run:
        kubectl apply -f app-deployment.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service app-service --url
        kubectl get deployments  
    
